### ISSUE TITLE
Context Diagram

### ISSUE THREAD

**Issue by woods16** [F18MIS4173Team6/Team6#13]
Remember that (for this milestone) the context diagram establishes the project scope and boundaries by depicting the system’s interfaces with external parties.  In milestone 3, the context diagram will be provide anchor for the complete Data Flow Diagram package

**Comment by kinneyp17** [comment]
<img width="485" alt="context diagram beagle and bee apiary ss" src="https://user-images.githubusercontent.com/42791034/46631961-01390300-cb17-11e8-8710-6f4de26cebcb.png">

**Comment by kinneyp17** [comment]
I added email functionality based on off something I saw on the Use Case Diagram. I think its a great idea. I am clueless on how we would code that though.
