### ISSUE TITLE
Use Case Package

### ISSUE THREAD

**Issue by woods16** [F18MIS4173Team6/Team6#14]
Executive Summary with Narrative and Conclusions
Use Case Diagram
Fully Detailed Use Case Specifications
Preliminary Non-functional Requirements

**Comment by woods16** [comment]
[UseCase fillable Template.docx](https://github.com/F18MIS4173Team6/Team6/files/2453588/UseCase.fillable.Template.docx)

**Comment by dunstonp14** [comment]
[USE CASE DIAGRAM.docx](https://github.com/F18MIS4173Team6/Team6/files/2454101/USE.CASE.DIAGRAM.docx)
Use Case Diagram

**Comment by boutersej16** [comment]
[Login Usecase.docx](https://github.com/F18MIS4173Team6/Team6/files/2454135/Login.Usecase.docx)

**Comment by dunstonp14** [comment]
[Hive Information Use Case.docx](https://github.com/F18MIS4173Team6/Team6/files/2454176/Hive.Information.Use.Case.docx)

**Comment by boutersej16** [comment]
[Report Generation Use Case.docx](https://github.com/F18MIS4173Team6/Team6/files/2454318/Report.Generation.Use.Case.docx)

**Comment by woods16** [comment]
[UseCase_Location.docx](https://github.com/F18MIS4173Team6/Team6/files/2456734/UseCase_Location.docx)
[UseCase_Queen and Colony.docx](https://github.com/F18MIS4173Team6/Team6/files/2456735/UseCase_Queen.and.Colony.docx)
[UseCase_Vendor.docx](https://github.com/F18MIS4173Team6/Team6/files/2456736/UseCase_Vendor.docx)
[UseCase_Hive Check.docx](https://github.com/F18MIS4173Team6/Team6/files/2456737/UseCase_Hive.Check.docx)
[UseCase_Inventory.docx](https://github.com/F18MIS4173Team6/Team6/files/2456738/UseCase_Inventory.docx)

**Comment by kinneyp17** [comment]
[Low inventory temporal trigger.docx](https://github.com/F18MIS4173Team6/Team6/files/2458168/Low.inventory.temporal.trigger.docx)

**Comment by woods16** [comment]
[UseCase_Colony.docx](https://github.com/F18MIS4173Team6/Team6/files/2458433/UseCase_Colony.docx)
[UseCase_Hive Check.docx](https://github.com/F18MIS4173Team6/Team6/files/2458434/UseCase_Hive.Check.docx)
[UseCase_Inventory.docx](https://github.com/F18MIS4173Team6/Team6/files/2458435/UseCase_Inventory.docx)
[UseCase_Location.docx](https://github.com/F18MIS4173Team6/Team6/files/2458436/UseCase_Location.docx)
[UseCase_Queen.docx](https://github.com/F18MIS4173Team6/Team6/files/2458437/UseCase_Queen.docx)
[UseCase_Vendor.docx](https://github.com/F18MIS4173Team6/Team6/files/2458438/UseCase_Vendor.docx)

**Comment by dunstonp14** [comment]
[USE CASE DIAGRAM.docx](https://github.com/F18MIS4173Team6/Team6/files/2458444/USE.CASE.DIAGRAM.docx)

**Comment by dunstonp14** [comment]
[Hive Information Use Case.docx](https://github.com/F18MIS4173Team6/Team6/files/2458445/Hive.Information.Use.Case.docx)

**Comment by boutersej16** [comment]
[Login Usecase_Updated.docx](https://github.com/F18MIS4173Team6/Team6/files/2458505/Login.Usecase_Updated.docx)
[Report Generation Use Case_Updated.docx](https://github.com/F18MIS4173Team6/Team6/files/2458506/Report.Generation.Use.Case_Updated.docx)

**Comment by woods16** [comment]
![image](https://user-images.githubusercontent.com/42754256/46677100-ee264180-cbaf-11e8-9620-25683c31be4c.png)
