### ISSUE TITLE
Corrections to Analysis Package

### ISSUE THREAD

**Issue by woods16** [F18MIS4173Team6/Team6#19]
Review comments from Dr. K and Victor. Incorporate updates to Analysis package to include updated Context Diagram.

**Comment by dunstonp14** [comment]
[Updated.Use.Cases.from.MS.2.docx](https://github.com/F18MIS4173Team6/Team6/files/2499564/Updated.Use.Cases.from.MS.2.docx)
updated used case Hive Information

**Comment by kinneyp17** [comment]
<img width="604" alt="beagle and bee context diagram updated 10-20" src="https://user-images.githubusercontent.com/42791034/47314541-f0f14f80-d60f-11e8-840e-8ae0b4aba15b.png">

**Comment by kinneyp17** [comment]
Updated context diagram

**Comment by woods16** [comment]
[Updated_MS 2 Analysis Report_Synergistic Solutions.docx](https://github.com/F18MIS4173Team6/Team6/files/2503836/Updated_MS.2.Analysis.Report_Synergistic.Solutions.docx)

**Comment by boutersej16** [comment]
[Report Generation Use Case_Updated.docx](https://github.com/F18MIS4173Team6/Team6/files/2503968/Report.Generation.Use.Case_Updated.docx)

**Comment by woods16** [comment]
Updated with Report Generation Use Case update.
[Updated_MS 2 Analysis Report_Synergistic Solutions.docx](https://github.com/F18MIS4173Team6/Team6/files/2504126/Updated_MS.2.Analysis.Report_Synergistic.Solutions.docx)

**Comment by kinneyp17** [comment]
<img width="605" alt="context diagram beagle and bee 10-20 2" src="https://user-images.githubusercontent.com/42791034/47332817-91fefb00-d64e-11e8-8962-1179b614e763.png">
Context diagram w/ employee information
