### ISSUE TITLE
Mock-ups – Forms and Reports

### ISSUE THREAD

**Issue by woods16** [F18MIS4173Team6/Team6#21]
Prototypes from VB or html

**Comment by boutersej16** [comment]
[MIS4173Mockups_jjbouterse.docx](https://github.com/F18MIS4173Team6/Team6/files/2499171/MIS4173Mockups_jjbouterse.docx)

**Comment by boutersej16** [comment]
[MIS4173ReportMockups_JJbouterse.docx](https://github.com/F18MIS4173Team6/Team6/files/2499234/MIS4173ReportMockups_JJbouterse.docx)
