### ISSUE TITLE
Program Plan

### ISSUE THREAD

**Issue by woods16** [F18MIS4173Team6/Team6#23]
Which programs will we have? What tasks will each accomplish? What are the inputs and outputs for each program? Define the detailed logic (processing) that turns the inputs into outputs.

Include:
1) The list of programs planned with a description of what each program will do
2) Pseducode, flowchart, or IPO chart which outlines the processes and logic of each program
3) Inputs and outputs for each program (may be included in IPO chart if we choose IPO to outline processes)

**Comment by kinneyp17** [comment]
[Programming Plan Beagle and bee apiary.docx](https://github.com/F18MIS4173Team6/Team6/files/2499681/Programming.Plan.Beagle.and.bee.apiary.docx)
