### ISSUE TITLE
Navigation Diagrams

### ISSUE THREAD

**Issue by woods16** [F18MIS4173Team6/Team6#24]
How will the user get around in the system?

**Comment by dunstonp14** [comment]
[NAVGATION NAVIGATIONcx](https://github.com/F18MIS4173Team6/Team6/files/2497714/NAVGATION.DESIGN.docx)

**Comment by dunstonp14** [comment]
[NAVIGATION DIAGRAM.docx](https://github.com/F18MIS4173Team6/Team6/files/2499546/NAVIGATION.DIAGRAM.docx)

**Comment by woods16** [comment]
Added the Hive Check and Employee Admin.. looked great, Phyllis, thank you!
[Navigation Diagram.docx](https://github.com/F18MIS4173Team6/Team6/files/2503625/Navigation.Diagram.docx)
