### ISSUE TITLE
Hardware & Software Specifications

### ISSUE THREAD

**Issue by woods16** [F18MIS4173Team6/Team6#25]

**Comment by dunstonp14** [comment]
[Hardware and Software Specification.docx](https://github.com/F18MIS4173Team6/Team6/files/2497716/Hardware.and.Software.Specification.docx)

**Comment by woods16** [comment]
[Hardware and Software Specification.docx](https://github.com/F18MIS4173Team6/Team6/files/2502444/Hardware.and.Software.Specification.docx)
