### ISSUE TITLE
PowerPoint for Class Presentation

### ISSUE THREAD

**Issue by woods16** [F18MIS4173Team6/Team6#26]

**Comment by dunstonp14** [comment]
[MS3 Design Presentation.pptx](https://github.com/F18MIS4173Team6/Team6/files/2499593/MS3.Design.Presentation.pptx)

**Comment by woods16** [comment]
[MS3 Presentation_Synergistic Solutions.pptx](https://github.com/F18MIS4173Team6/Team6/files/2504128/MS3.Presentation_Synergistic.Solutions.pptx)

**Comment by woods16** [comment]
[MS3 Design Report_Synergistic Solutions.docx](https://github.com/F18MIS4173Team6/Team6/files/2508155/MS3.Design.Report_Synergistic.Solutions.docx)

**Comment by woods16** [comment]
[MS3 Presentation_Synergistic Solutions.pptx](https://github.com/F18MIS4173Team6/Team6/files/2508157/MS3.Presentation_Synergistic.Solutions.pptx)
