### ISSUE TITLE
Narrative and screen shots from presentation

### ISSUE THREAD

**Issue by woods16** [F18MIS4173Team6/Team6#36]
1)	Employee Login – Phyllis 
2)	Add/Update Queen – Sarah 
3)	Add/Update Colony – Sarah 
4)	Add/Update/Delete Vendor – Sarah 
5)	Add/Update Location – Sarah 
6)	Add/Update/Delete Hive – Sarah 
7)	Add/Update/Delete Inventory Items – Phillip 
8)	Log Hive Check Information – Phillip
9)	Report Generation - Joe
10)	Enter/Edit Employee Information – Phyllis

**Comment by dunstonp14** [comment]
[Manager Login and Employee Training doc.docx](https://github.com/F18MIS4173Team6/Team6/files/2551146/Manager.Login.and.Employee.Training.doc.docx)

**Comment by kinneyp17** [comment]
[Training documentation Beekeeper.docx](https://github.com/F18MIS4173Team6/Team6/files/2569710/Training.documentation.Beekeeper.docx)
[Training documentation- Office Employee.docx](https://github.com/F18MIS4173Team6/Team6/files/2569711/Training.documentation-.Office.Employee.docx)
