### ISSUE TITLE
Narrative & screen shots for training all users

### ISSUE THREAD

**Issue by woods16** [F18MIS4173Team6/Team6#38]
1)	Employee Login – Phyllis 
2)	Add/Update Queen – Sarah 
3)	Add/Update Colony – Sarah 
4)	Add/Update/Delete Vendor – Sarah 
5)	Add/Update Location – Sarah 
6)	Add/Update/Delete Hive – Sarah 
7)	Add/Update/Delete Inventory Items – Phillip 
8)	Log Hive Check Information – Phillip
9)	Report Generation - Joe
10)	Enter/Edit Employee Information – Phyllis

**Comment by dunstonp14** [comment]
[Manager Login and Employee Training doc.docx](https://github.com/F18MIS4173Team6/Team6/files/2551088/Manager.Login.and.Employee.Training.doc.docx)
[Training doc for employee.docx](https://github.com/F18MIS4173Team6/Team6/files/2551089/Training.doc.for.employee.docx)

**Comment by dunstonp14** [comment]
[Manager Login and Employee Training doc.docx](https://github.com/F18MIS4173Team6/Team6/files/2551139/Manager.Login.and.Employee.Training.doc.docx)

[Training doc for employee.docx](https://github.com/F18MIS4173Team6/Team6/files/2551138/Training.doc.for.employee.docx)

**Comment by dunstonp14** [comment]
[Training doc for employee.docx](https://github.com/F18MIS4173Team6/Team6/files/2551145/Training.doc.for.employee.docx)

**Comment by kinneyp17** [comment]
[Training documentation- Office Employee.docx](https://github.com/F18MIS4173Team6/Team6/files/2569712/Training.documentation-.Office.Employee.docx)

**Comment by boutersej16** [comment]
[MS5.Training.Report_Synergistic.Solutions.docx](https://github.com/F18MIS4173Team6/Team6/files/2570124/MS5.Training.Report_Synergistic.Solutions.docx)

added my training on to Phillip's document
