### ISSUE TITLE
Technical Documentation (User Manual)

### ISSUE THREAD

**Issue by woods16** [F18MIS4173Team6/Team6#39]
1)	Employee Login – Phyllis 
2)	Add/Update Queen – Sarah 
3)	Add/Update Colony – Sarah 
4)	Add/Update/Delete Vendor – Sarah 
5)	Add/Update Location – Sarah 
6)	Add/Update/Delete Hive – Sarah 
7)	Add/Update/Delete Inventory Items – Phillip 
8)	Log Hive Check Information – Phillip
9)	Report Generation - Joe
10)	Enter/Edit Employee Information – Phyllis

**Comment by dunstonp14** [comment]
[Login and employee Technical doc..docx](https://github.com/F18MIS4173Team6/Team6/files/2551092/Login.and.employee.Technical.doc.docx)

**Comment by dunstonp14** [comment]
[Login and employee Technical doc..docx](https://github.com/F18MIS4173Team6/Team6/files/2551135/Login.and.employee.Technical.doc.docx)

**Comment by kinneyp17** [comment]
[Technical training documentation- Beekeeper and Office Employee.docx](https://github.com/F18MIS4173Team6/Team6/files/2569714/Technical.training.documentation-.Beekeeper.and.Office.Employee.docx)

**Comment by boutersej16** [comment]
Updated User Manual in OneDrive
