### ISSUE TITLE
Complete and Consolidated Report

### ISSUE THREAD

**Issue by woods16** [F18MIS4173Team6/Team6#46]
Title Page
Table of Contents

Section 1.  Project Description

Executive Summary with Narrative and Conclusions
Current Environment
Proposed System Objectives and Constraints
Expected Benefits
Stakeholders
Context Diagram

Section 2.  Analysis 

Executive Summary with Narrative and Conclusions
Use Case Diagram
Fully Detailed Use Case Specifications
Supplement Specifications

Section 3. Design

Executive Summary with Narrative and Conclusions
Complete Data Flow Diagram Package
Hardware and Software Specification
Navigation Diagram
Forms
Mockup Reports
Entity Relationship Diagrams
Standard Naming Conventions

Section 4. Structured Walkthrough

Program Documentation
List of Programs Created
IPO chart outlining the logic and processes of each program
Printout of program code for each program
Explanation of challenges, problems and discoveries
Test Plans
Data used for testing
Explanation of challenges, problems and discoveries

Section 5. Training

Executive Summary with Narrative and Conclusions
A Narrative and screen shots from your presentation.
Chosen training mode for training your other users
Narrative and screen shots for training these users
User manual and documentation

Section 6. Project Assessment

Project Plan (showing Completion Accomplishments)
Project Assessment (by each member)
Lessons Learned during the project (by group)

Appendix

All Milestone Reports, Timesheets (consolidated)

**Comment by woods16** [comment]
Need to work on Section 4 and need to complete assessments to add to the report. May need updated screenshots since some include old mockups with numbers instead of names in the dropdowns.
[MS6 Final Deliverable_Synergistic Solutions.docx](https://github.com/F18MIS4173Team6/Team6/files/2637306/MS6.Final.Deliverable_Synergistic.Solutions.docx)

**Comment by woods16** [comment]
Still working on section 4 "lessons learned" but wanted to upload the latest update before taking a small break today for dinner.. 
[MS6 Final Deliverable_Synergistic Solutions.docx](https://github.com/F18MIS4173Team6/Team6/files/2637539/MS6.Final.Deliverable_Synergistic.Solutions.docx)

**Comment by dunstonp14** [comment]
[Individual Assessment.docx](https://github.com/F18MIS4173Team6/Team6/files/2637838/Individual.Assessment.docx)

**Comment by woods16** [comment]
Updated with Section 4. Will resubmit once I get IPO and individual assessments from Philip & Joe and final timesheets. Feel free to estimate your time for tomorrow, I'd love to get the timesheets and report squared away tonight! We're so close, team!!
[MS6 Final Deliverable_Synergistic Solutions.docx](https://github.com/F18MIS4173Team6/Team6/files/2639941/MS6.Final.Deliverable_Synergistic.Solutions.docx)

**Comment by boutersej16** [comment]
My assessment is added, almost there!

[MS6.Final.Deliverable_Synergistic.Solutions.docx](https://github.com/F18MIS4173Team6/Team6/files/2641449/MS6.Final.Deliverable_Synergistic.Solutions.docx)

**Comment by kinneyp17** [comment]
[mis 4173 project assessment.docx](https://github.com/F18MIS4173Team6/Team6/files/2641540/mis.4173.project.assessment.docx)

**Comment by woods16** [comment]
[MS6 Final Deliverable_Synergistic Solutions.docx](https://github.com/F18MIS4173Team6/Team6/files/2642227/MS6.Final.Deliverable_Synergistic.Solutions.docx)
Waiting on IPO and timesheets, but do one of you mind checking to see if the PDFs of the code under the testing section will pull up on your system w/o the source PDF (which is on my computer)? Thank you!!

**Comment by woods16** [comment]
[MS6 Final Deliverable_Synergistic Solutions.docx](https://github.com/F18MIS4173Team6/Team6/files/2644749/MS6.Final.Deliverable_Synergistic.Solutions.docx)

**Comment by woods16** [comment]
[MS6 Final Deliverable_Synergistic Solutions.docx](https://github.com/F18MIS4173Team6/Team6/files/2646572/MS6.Final.Deliverable_Synergistic.Solutions.docx)
