### ISSUE TITLE
Final PowerPoint Presentation

### ISSUE THREAD

**Issue by woods16** [F18MIS4173Team6/Team6#48]

**Comment by boutersej16** [comment]
[MS6_Presentation.pptx](https://github.com/F18MIS4173Team6/Team6/files/2637831/MS6_Presentation.pptx)

slide 8 - not sure how to add scope/boundires can we just talk about those things with slide as backdrop?

**Comment by woods16** [comment]
I think so, Joe - that makes sense! This looks great, thank you for your work! Updated just a little to fix the Use Case Diagram and threw in a few bullets to the blank ones though I'm not in love with them and would like feedback. :)
[MS6_Presentation.pptx](https://github.com/F18MIS4173Team6/Team6/files/2639931/MS6_Presentation.pptx)

**Comment by woods16** [comment]
[Sarah speech.docx](https://github.com/F18MIS4173Team6/Team6/files/2645803/Sarah.speech.docx)

**Comment by woods16** [comment]
[MS6_Presentation.pptx](https://github.com/F18MIS4173Team6/Team6/files/2646469/MS6_Presentation.pptx)
I have no idea if I updated anything in here since the last time I posted it, so thought I'd just repost anyway, just in case.

**Comment by woods16** [comment]
[MS6_Presentation.pptx](https://github.com/F18MIS4173Team6/Team6/files/2646487/MS6_Presentation.pptx)

**Comment by kinneyp17** [comment]
[MS 6 Speech.docx](https://github.com/F18MIS4173Team6/Team6/files/2646602/MS.6.Speech.docx)
